sudo: false
language: rust
cache: cargo

# necessary for kcov
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev # required for the --verify flag of kcov
      - libiberty-dev

rust:
  - nightly
  - beta
  - stable
  - 1.12.0

branches:
  only:
    - master
    - /v?\d(\.\d)*/

before_script:
  - export PATH=$PATH:~/.cargo/bin

script:
  - cargo build
  - cargo test
  - cargo doc --no-deps
after_success:
  # NB: kcov only works on linux
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./ci/install-kcov.sh && ./ci/coverage.sh; fi

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=nightly
    - RUSTFLAGS="-C link-dead-code" # Enable better code coverage at the cost of binary size

notifications:
  email:
    on_success: never

os:
  - linux
  - osx
