sudo: false
language: rust
cache: cargo

# necessary for kcov
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev # required for the --verify flag of kcov
      - libiberty-dev

matrix:
  include:
    - rust: nightly
      sudo: required # Work around for travis-ci/travis-ci#9061
      cache: false
      env:
        - FEATURE_FLAGS="--features nightly"
        - RUSTFLAGS="-C link-dead-code" # Enable better code coverage at the cost of binary size
      after_success:
        - ./ci/install-kcov.sh && ./ci/coverage.sh

    - rust: beta
    - rust: stable
    - rust: 1.16.0
    - os: osx
      rust: stable

branches:
  only:
    - master
    - /v?\d(\.\d)*/

before_script:
  - export PATH=$PATH:~/.cargo/bin

script:
  - cargo check $FEATURE_FLAGS
  - cargo test $FEATURE_FLAGS

notifications:
  email:
    on_success: never
