sudo: false
language: rust
cache: cargo

rust:
  - nightly
  - beta
  - stable
    #- 1.12.0 # FIXME: revisit earliest supported compiler

before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$PATH:$HOME/.local/bin
  - export PATH=$PATH:~/.cargo/bin

script:
  - cargo build
  - cargo test
  - cargo doc --no-deps
after_success:
  # NB: only upload linux master docs to avoid conflicting with the osx build
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then $travis-cargo --only stable doc-upload; fi

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=nightly

notifications:
  email:
    on_success: never

os:
  - linux
  - osx
