environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc
    RUST_VERSION: nightly
  - TARGET: x86_64-pc-windows-msvc
    RUST_VERSION: beta
  - TARGET: x86_64-pc-windows-msvc
    RUST_VERSION: stable
  - TARGET: x86_64-pc-windows-msvc
    RUST_VERSION: 1.12.0

install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:RUST_VERSION}-${env:TARGET}.exe" -FileName "rust-init.exe"
  - ps: .\rust-init.exe /VERYSILENT /NORESTART /DIR="C:\rust" | Out-Null
  - ps: $env:PATH="$env:PATH;C:\rust\bin"
  - rustc -vV
  - cargo -vV

build: false

test_script:
  - cargo build
  - cargo test
