environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc
  - RUST_VERSION: nightly
  - RUST_VERSION: beta
  - RUST_VERSION: stable
  - RUST_VERSION: 1.12.0

install:
  - set PATH=C:\Program Files\Git\mingw64\bin;%PATH%
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -V
  - cargo -V

build: false

test_script:
  - cargo build
  - cargo test
