[package]
name = "shell"
version = "0.0.1"
authors = ["Ivan Petkov <ivanppetkov@gmail.com>"]

[features]
runtime = ["glob", "libc"]

[dependencies]
void = "*"

[dependencies.glob]
version = "0.2"
optional = true

[dependencies.libc]
version = "0.1"
optional = true
