[package]
name = "conch-parser"
version = "0.1.0"
authors = ["Ivan Petkov <ivanppetkov@gmail.com>"]
license = "MIT/Apache-2.0"

[features]
nightly = []

[dependencies]
clippy = { version = "~0.0.80", optional = true }
void = "1"
