[package]
name = "shell"
version = "0.0.1"
authors = ["Ivan Petkov <ivanppetkov@gmail.com>"]

[features]
runtime = ["glob", "libc", "winapi", "kernel32-sys"]

[dependencies]
void = "1"

[dependencies.glob]
version = "0.2"
optional = true

[dependencies.kernel32-sys]
version = "0.2.1"
optional = true

[dependencies.libc]
version = "0.2"
optional = true

[dependencies.winapi]
version = "0.2.5"
optional = true

[dev-dependencies]
tempdir = "0.3"
