[package]
name = "shell"
version = "0.0.1"
authors = ["Ivan Petkov <ivanppetkov@gmail.com>"]

[features]
runtime = ["glob", "libc", "winapi", "kernel32-sys"]

[dependencies]
void         = "1"
clippy       = { version = "^0.0",   optional = true }
glob         = { version = "0.2",    optional = true }
kernel32-sys = { version = "0.2.1",  optional = true }
libc         = { version = "0.2",    optional = true }
winapi       = { version = "0.2.5",  optional = true }

[dev-dependencies]
tempdir = "0.3"
